// <auto-generated />
using EveM_Curd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EveM_Curd.Migrations
{
    [DbContext(typeof(EventContext))]
    [Migration("20230322161549_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EveM_Curd.Models.EventExpense", b =>
                {
                    b.Property<string>("Expense_name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Expense_amount")
                        .HasColumnType("int");

                    b.Property<string>("Expense_date")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Expense_name");

                    b.ToTable("EventExpenses");
                });

            modelBuilder.Entity("EveM_Curd.Models.EventIncome", b =>
                {
                    b.Property<string>("Income_name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Income_amount")
                        .HasColumnType("int");

                    b.Property<string>("Income_date")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Income_name");

                    b.ToTable("EventIncomes");
                });
#pragma warning restore 612, 618
        }
    }
}
