// <auto-generated />
using EveM_Curd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EveM_Curd.Migrations
{
    [DbContext(typeof(EventContext))]
    [Migration("20230328120359_VendorDetail")]
    partial class VendorDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EveM_Curd.Models.EventDetail", b =>
                {
                    b.Property<int>("Event_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Event_id"));

                    b.Property<string>("Event_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Event_id");

                    b.ToTable("EventDetails");
                });

            modelBuilder.Entity("EveM_Curd.Models.EventExpense", b =>
                {
                    b.Property<int>("Expense_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Expense_id"));

                    b.Property<int>("Expense_amount")
                        .HasColumnType("int");

                    b.Property<string>("Expense_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expense_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Expense_id");

                    b.ToTable("EventExpenses");
                });

            modelBuilder.Entity("EveM_Curd.Models.EventIncome", b =>
                {
                    b.Property<int>("Income_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Income_id"));

                    b.Property<int>("Income_amount")
                        .HasColumnType("int");

                    b.Property<string>("Income_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Income_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Income_id");

                    b.ToTable("EventIncomes");
                });
#pragma warning restore 612, 618
        }
    }
}
